version: "3.9"

services:
  app:
    container_name: e-commerce_api
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&  
             python manage.py runserver 0.0.0.0:8000"
    # environment:
    #   - SECRET_KEY=dfjsklm90i4rn
    #   - DEBUG=1
    #   - ALLOWED_HOSTS=localhost,127.0.0.1
    #   - DB_HOST=db
    #   - DB_NAME=devdb
    #   - DB_USER=devuser
    #   - DB_PASS=changeme
    #   - DB_PORT=5432
    #   - DEBUG=1

    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data

    # environment:
    #   - POSTGRES_DB=devdb
    #   - POSTGRES_USER=devuser
    #   - POSTGRES_PASSWORD=changeme

    ports:
      - "5432:5432"

    env_file:
      - .env

volumes:
  dev-db-data:
  dev-static-data:
