# Generated by Django 5.0.3 on 2024-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandWithImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='brand_images')),
                ('gender', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
