# Generated by Django 5.0.3 on 2024-05-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_product_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
