# Generated by Django 5.0.3 on 2024-04-18 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_options_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+[0-9]{1,3})?[0-9]{9,15}$')])),
                ('otp', models.CharField(max_length=6)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
