# Generated by Django 5.0.3 on 2024-04-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='mobile_number',
        ),
    ]
