# Generated by Django 5.0.3 on 2024-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_otp_mobile_number'),
        ('api', '0003_offer_product_number_of_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='api.product'),
        ),
    ]
