# Generated by Django 5.0.3 on 2024-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(related_name='categories', to='api.parentcategory'),
        ),
    ]
