# Generated by Django 5.0.3 on 2024-04-26 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_category_parent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Men', 'Kişilər'), ('Women', 'Qadınlar'), ('Oğlanlar', 'Boys'), ('Girls', 'Qızlar')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.ManyToManyField(related_name='categories', to='api.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gender'),
        ),
    ]
