# Generated by Django 5.0.3 on 2024-04-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gender_alter_category_name_category_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='gender',
            field=models.ManyToManyField(related_name='parent_categories', to='api.gender'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='type',
            field=models.CharField(choices=[('Men', 'Kişilər'), ('Women', 'Qadınlar'), ('Oğlanlar', 'Boys'), ('Girls', 'Qızlar')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
