# Generated by Django 5.0.3 on 2024-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_parentcategory_gender_alter_gender_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
