# Generated by Django 5.0.3 on 2024-04-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_parentcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategory',
            name='gender',
        ),
    ]
