# Generated by Django 5.0.3 on 2024-04-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_parentcategory_gender_alter_parentcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='type',
            field=models.CharField(choices=[('Men', 'Kişilər'), ('Women', 'Qadınlar'), ('Boys', 'Oğlanlar'), ('Girls', 'Qızlar')], max_length=255, unique=True),
        ),
    ]
